### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by etcet** [forabi/pia-webext#1]
Hey, I just switched to Firefox and I'm miffed PIA doesn't have an extension, then I found yours! But, I have no idea how to use it. If I try to load the master zipped it says it's corrupted.

**Comment by forabi** [comment]
Sorry, I no longer have time to work on this. This repo is not configured to produce an extension file you could use in Firefox. Loading an extension requires signing the file with Mozilla's signing service. Also, last I tried the VPN connection was not stable. So I don't recommend using it for now, even for experimentation.

If you want an alternative VPN extension, ZenMate has recently updated their extension to be compatible with Firefox 57+.

**Comment by etcet** [comment]
No worries forabi, can you confirm that this code is under an MIT, Apache, or GPL license?

**Comment by forabi** [comment]
@etcet The code is MIT licensed (https://github.com/forabi/pia-webext/blob/d9f90eb4743e783d702825554e745e69ad0be535/package.json#L7)

The resources in `./dist`, however, are extracted from the official PIA extension for Chrome.
